In [5]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN
from sklearn.metrics import accuracy_score

In [6]:
df = pd.read_csv('df.csv')

In [7]:
df.head()

,Unnamed: 0,Latitude,Longitude,Monthly Charges,Total Charges,Churn Value,CLTV,Gender_Male,Senior Citizen_Yes,Partner_Yes,...,Streaming TV_Yes,Streaming Movies_No internet service,Streaming Movies_Yes,Contract_One year,Contract_Two year,Paperless Billing_Yes,Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check,tenure_group_encoded
0,0,33.964131,-118.272783,53.85,108.15,1,3239,True,False,False,...,False,False,False,False,False,True,False,False,True,0.0
1,1,34.059281,-118.307420,70.70,151.65,1,2701,False,False,False,...,False,False,False,False,False,True,False,True,False,0.0
2,2,34.048013,-118.293953,99.65,820.50,1,5372,False,False,False,...,True,False,True,False,False,True,False,True,False,0.0
3,3,34.062125,-118.315709,104.80,3046.05,1,5003,False,False,True,...,True,False,True,False,False,True,False,True,False,2.0
4,4,34.039224,-118.266293,103.70,5036.30,1,5340,True,False,False,...,True,False,True,False,False,True,False,False,False,4.0

In [8]:
df = df.drop('Unnamed: 0',axis=1)

In [9]:
df

,Latitude,Longitude,Monthly Charges,Total Charges,Churn Value,CLTV,Gender_Male,Senior Citizen_Yes,Partner_Yes,Dependents_Yes,...,Streaming TV_Yes,Streaming Movies_No internet service,Streaming Movies_Yes,Contract_One year,Contract_Two year,Paperless Billing_Yes,Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check,tenure_group_encoded
0,33.964131,-118.272783,53.85,108.15,1,3239,True,False,False,False,...,False,False,False,False,False,True,False,False,True,0.0
1,34.059281,-118.307420,70.70,151.65,1,2701,False,False,False,True,...,False,False,False,False,False,True,False,True,False,0.0
2,34.048013,-118.293953,99.65,820.50,1,5372,False,False,False,True,...,True,False,True,False,False,True,False,True,False,0.0
3,34.062125,-118.315709,104.80,3046.05,1,5003,False,False,True,True,...,True,False,True,False,False,True,False,True,False,2.0
4,34.039224,-118.266293,103.70,5036.30,1,5340,True,False,False,True,...,True,False,True,False,False,True,False,False,False,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,34.341737,-116.539416,21.15,1419.40,0,5306,False,False,False,False,...,False,True,False,False,True,True,False,False,False,5.0
7039,34.667815,-117.536183,84.80,1990.50,0,2140,True,False,True,True,...,True,False,True,True,False,True,False,False,True,1.0
7040,34.559882,-115.637164,103.20,7362.90,0,5560,False,False,True,True,...,True,False,True,True,False,True,True,False,False,5.0
7041,34.167800,-116.864330,29.60,346.45,0,2793,False,False,True,True,...,False,False,False,False,False,True,False,True,False,0.0
7042,34.424926,-117.184503,105.65,6844.50,0,5097,True,False,False,False,...,True,False,True,False,True,True,False,False,False,5.0

In [10]:
x = df.drop('Churn Value',axis=1)

In [11]:
print(x)

       Latitude   Longitude  Monthly Charges  Total Charges  CLTV  \
0     33.964131 -118.272783            53.85         108.15  3239
1     34.059281 -118.307420            70.70         151.65  2701
2     34.048013 -118.293953            99.65         820.50  5372
3     34.062125 -118.315709           104.80        3046.05  5003
4     34.039224 -118.266293           103.70        5036.30  5340
...         ...         ...              ...            ...   ...
7038  34.341737 -116.539416            21.15        1419.40  5306
7039  34.667815 -117.536183            84.80        1990.50  2140
7040  34.559882 -115.637164           103.20        7362.90  5560
7041  34.167800 -116.864330            29.60         346.45  2793
7042  34.424926 -117.184503           105.65        6844.50  5097

      Gender_Male  Senior Citizen_Yes  Partner_Yes  Dependents_Yes  \
0            True               False        False           False
1           False               False        False            True
2           False               False        False            True
3           False               False         True            True
4            True               False        False            True
...           ...                 ...          ...             ...
7038        False               False        False           False
7039         True               False         True            True
7040        False               False         True            True
7041        False               False         True            True
7042         True               False        False           False

      Phone Service_Yes  ...  Streaming TV_Yes  \
0                  True  ...             False
1                  True  ...             False
2                  True  ...              True
3                  True  ...              True
4                  True  ...              True
...                 ...  ...               ...
7038               True  ...             False
7039               True  ...              True
7040               True  ...              True
7041              False  ...             False
7042               True  ...              True

      Streaming Movies_No internet service  Streaming Movies_Yes  \
0                                    False                 False
1                                    False                 False
2                                    False                  True
3                                    False                  True
4                                    False                  True
...                                    ...                   ...
7038                                  True                 False
7039                                 False                  True
7040                                 False                  True
7041                                 False                 False
7042                                 False                  True

      Contract_One year  Contract_Two year  Paperless Billing_Yes  \
0                 False              False                   True
1                 False              False                   True
2                 False              False                   True
3                 False              False                   True
4                 False              False                   True
...                 ...                ...                    ...
7038              False               True                   True
7039               True              False                   True
7040               True              False                   True
7041              False              False                   True
7042              False               True                   True

      Payment Method_Credit card (automatic)  Payment Method_Electronic check  \
0                                      False                            False
1                                      False                             True
2                                      False                             True
3                                      False                             True
4                                      False                            False
...                                      ...                              ...
7038                                   False                            False
7039                                   False                            False
7040                                    True                            False
7041                                   False                             True
7042                                   False                            False

      Payment Method_Mailed check  tenure_group_encoded
0                            True                   0.0
1                           False                   0.0
2                           False                   0.0
3                           False                   2.0
4                           False                   4.0
...                           ...                   ...
7038                        False                   5.0
7039                         True                   1.0
7040                        False                   5.0
7041                        False                   0.0
7042                        False                   5.0

[7043 rows x 33 columns]

In [12]:
y = df['Churn Value']

In [13]:
print(y)

0       1
1       1
2       1
3       1
4       1
       ..
7038    0
7039    0
7040    0
7041    0
7042    0
Name: Churn Value, Length: 7043, dtype: int64

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

# DecisionTreeClassifier

In [15]:
model_dt = DecisionTreeClassifier(criterion='gini',random_state=100,max_depth=7,min_samples_leaf=8)

In [16]:
model_dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=7, min_samples_leaf=8, random_state=100)

In [17]:
y_pred = model_dt.predict(x_test)

In [18]:
accuracy = accuracy_score(y_test, y_pred)

In [19]:
print(accuracy)

0.7778566359119943

since we can ses that our accuracy is less beaucse data is imbalencd so we need to make it balenced by methods like upsampling or down sampling

In [20]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.80      0.93      0.86      1022
           1       0.67      0.38      0.48       387

    accuracy                           0.78      1409
   macro avg       0.73      0.65      0.67      1409
weighted avg       0.76      0.78      0.76      1409

In [21]:
print(confusion_matrix(y_test,y_pred))

[[950  72]
 [241 146]]

so we can see its biased model so we need to do upsampling to improve our model to do actual prediction

In [22]:
print("Missing values before fix:")
print(x.isnull().sum()[x.isnull().sum() > 0])
x = x.fillna(0)

Missing values before fix:
tenure_group_encoded    11
dtype: int64

In [26]:
from sklearn.ensemble import RandomForestClassifier

# makng data balnced using upsampling

In [27]:
sm = SMOTEENN()
X_resampled1, y_resampled1 = sm.fit_resample(x,y)

In [28]:
xr_train1,xr_test1,yr_train1,yr_test1=train_test_split(X_resampled1, y_resampled1,test_size=0.2)

In [29]:
model_rf_smote=RandomForestClassifier(n_estimators=1000, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [30]:
model_rf_smote.fit(xr_train1,yr_train1)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, n_estimators=1000,
                       random_state=100)

In [31]:
yr_predict1 = model_rf_smote.predict(xr_test1)

In [32]:
model_score_r1 = model_rf_smote.score(xr_test1, yr_test1)

In [33]:
print(model_score_r1)
print(metrics.classification_report(yr_test1, yr_predict1))

0.9102803738317757
              precision    recall  f1-score   support

           0       0.91      0.87      0.89       445
           1       0.91      0.94      0.92       625

    accuracy                           0.91      1070
   macro avg       0.91      0.90      0.91      1070
weighted avg       0.91      0.91      0.91      1070

In [34]:
from xgboost import XGBClassifier
model_xg = XGBClassifier()

In [35]:
model_xg.fit(xr_train1,yr_train1)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [36]:
y_xg = model_xg.predict(xr_test1)

In [37]:
acc3 = accuracy_score(yr_test1, y_xg)
print(f"XGBoost Accuracy: {acc3}")

XGBoost Accuracy: 0.9364485981308411

In [38]:
import pickle

In [39]:
filename = 'model.sav'

In [40]:
pickle.dump(model_xg, open(filename, 'wb'))

In [41]:
load_model = pickle.load(open(filename, 'rb'))

In [43]:
model_score_r1 = load_model.score(xr_test1,yr_test1)

In [44]:
model_score_r1

0.9364485981308411